name: KPGA Results Scraper

on:
  # workflow_dispatch: # GitHub Actions 탭에서 수동으로 실행 가능하게 함
  schedule:
    # 매일 오전 9시 30분(KST)에 실행 (UTC 기준 00:30)
    # 참고: GitHub Actions 스케줄은 약간의 지연이 있을 수 있습니다.
    - cron: '30 0 * * *'

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest # 실행 환경 지정 (리눅스 최신 버전)

    steps:
      - name: Checkout code # 저장소의 코드를 runner 환경으로 가져옴
        uses: actions/checkout@v4

      - name: Set up Python # 파이썬 환경 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 사용할 파이썬 버전 지정

      # ▼▼▼ 여기가 수정되었습니다 ▼▼▼
      - name: Install dependencies # requirements.txt 로 라이브러리 설치
        run: |
          python -m pip install --upgrade pip
          # requirements.txt 파일이 있으면 해당 파일로 라이브러리 설치
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # ▲▲▲ 여기가 수정되었습니다 ▲▲▲

      - name: Run scraper script # 파이썬 스크립트 실행
        env: # GitHub Secrets 값을 환경 변수로 주입
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python Golf_score.py # 실행할 파이썬 파일 이름

