name: Run KPGA Score Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # 오전 7시 (KST)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 python-telegram-bot webdriver-manager

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget unzip xvfb
        curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Run KPGA bot
      run: |
        python golf_score.py
