name: Golf Score KPGA Bot (HTML 파싱)

on:
  schedule:
    - cron: '0 22 * * *'  # 오전 7시 (KST)
    - cron: '8 8 * * *'   # 오후 5시 (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable wget curl unzip gnupg
        sudo ln -sf /usr/bin/google-chrome /usr/bin/chrome || true

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run KPGA Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python golf_score.py
