name: Golf Score OCR Bot (KPGA)

on:
  schedule:
    - cron: '0 22 * * *'  # 오전 7시 KST
    - cron: '8 8 * * *'   # 오후 5시 KST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Snap 타임아웃 방지

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr libtesseract-dev
        which tesseract

    - name: Install Chromium & ChromeDriver (APT 방식)
      run: |
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run OCR Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python golf_score.py
